name: Build and Push Image
on:
  push:
  pull_request:
  schedule:
  - cron: '0 12 * * MON'  # Run every Monday
jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
        - crs-v3.3.2-waf1
        - crs-v3.3.2-waf2
#        - crs-v3.2.0-waf1
#        - crs-v3.3.0-waf1
#        - crs-v3.3.0-waf2

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: puzzle/centos-apache-modsecurity
        tags: ${{ matrix.tag }}
        containerfiles: |
          ./Dockerfile

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
